name: Publish to Google App Engine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install google-cloud-sdk-app-engine-go
      - name: Deploy to Google App Engine
        uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_name: ${{ secrets.PROJECT_ID }}